<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Correct and clean exception handling - gbadev.org forum archive</title>
        <link rel="stylesheet" href="/forum-archive/static/pure-min.css" />
        <link rel="stylesheet" href="/forum-archive/static/main.css" />
    </head>
    <body>
        <h1>gbadev.org forum archive</h1>

        <i>This is a read-only mirror of the content originally found on forum.gbadev.org
        (now offline), salvaged from Wayback machine copies. </i><br />

        <h2>OffTopic > Correct and clean exception handling</h2>
<div id="posts">
<div class="post">
    <h4>#121281 - Mr Snowflake - Sun Mar 11, 2007 2:46 am</h4>
    <div class="postbody"><span class="postbody">For the same project as in my previous <a class="postlink" href="http://forum.gbadev.org/viewtopic.php?t=12492" target="_blank">topic</a> I, obviously, need exception handling. But I don't know how to handle, cleanly, a specific situation: Say I have a function:
<br/>
</span><table align="center" border="0" cellpadding="3" cellspacing="1" width="90%"><tr> <td><span class="genmed"><b>Code:</b></span></td> </tr> <tr> <td class="code">
<br/>
function toBeCalled() throws SomeException{
<br/>
  for(String name : nameList)
<br/>
    if(name.compareTo("") == 0)
<br/>
      throw new SomeException();
<br/>
}</td> </tr></table><span class="postbody">
<br/>
If I call this function from an other function, and I need to keep toBeCalled() looping through nameList even if an exception is encountered (in this case, I just want to display a message saying name is empty, but it's not critical, so I can continue). How should I do it?
<br/>
- I could catch the exception in toBeCalled(), and then jump back in the for lus with goto. But this is really bad and with this foreach loop, I don't even think it is possible to pickup where I left. but then there's the problem that I do not know how to output the error and if to output the error when in toBeCalled().
<br/>
- I could keep a Vector with all the exceptions generated in toBeCalled(), but for some reason I don't really like this and I prefer having the exceptions outputted immediately.
<br/>
<br/>
In my project I use the foreach loop. And it is a Java project.
<br/>
<br/>
And to improve my English writing: How is my English?? :)<br/>_________________<br/><a class="postlink" href="http://www.mrsnowflake.be" target="_blank">http://www.mrsnowflake.be</a></span><span class="gensmall"></span></div>    
</div>
<div class="post">
    <h4>#121282 - tepples - Sun Mar 11, 2007 2:55 am</h4>
    <div class="postbody"><span class="postbody">If you absolutely must use <span style="font-weight: bold">throw</span>, then make a list of exceptions and throw that at the end of the function.<br/>_________________<br/>-- Where is he?
<br/>
-- Who?
<br/>
-- You know, the human.
<br/>
-- I think he moved to Tilwick.</span><span class="gensmall"></span></div>    
</div>
<div class="post">
    <h4>#121283 - sgeos - Sun Mar 11, 2007 3:17 am</h4>
    <div class="postbody"><span class="postbody">Do you need to use throw at all?  I guess I would do something like this:
<br/>
</span><table align="center" border="0" cellpadding="3" cellspacing="1" width="90%"><tr> <td><span class="genmed"><b>Code:</b></span></td> </tr> <tr> <td class="code">
<br/>
error = 0;
<br/>
foreach (...)
<br/>
   if (test)
<br/>
      // OK
<br/>
   else
<br/>
      error++;
<br/>
<br/>
if (0 != error)
<br/>
{
<br/>
   printErrorMessage(error);
<br/>
   throw exception(error);
<br/>
}</td> </tr></table><span class="postbody">
<br/>
<br/>
Your English is fine.  Read quality English and practice if you want to improve your writing.
<br/>
<br/>
-Brendan</span><span class="gensmall"></span></div>    
</div>
<div class="post">
    <h4>#121299 - keldon - Sun Mar 11, 2007 9:42 am</h4>
    <div class="postbody"><span class="postbody">It is better not to print your error messages when you are throwing; and only catch an exception when you wish to handle it in some way, even if that means you are only catching it to deallocate anything that needs to deallocate and throw it again.
<br/>
<br/>
The problem many people make with exception handling is to catch exceptions that they don't wish to handle at the wrong time just so that their method does not throw an exception. You will often find that if you are catching an exception that the method that called you will also not get its result so it would have been easier if you threw that exception and passed on the responsibility of handling it to the one who should handle it.
<br/>
<br/>
Another thing to think about is the <a class="postlink" href="http://en.wikipedia.org/wiki/ACID" target="_blank">ACID</a> properties. If you are in an operation such as saving and you have an exception then you don't want to have overwritten your previous file with an unfinished one. So just make sure that you will not end up in a bad state after having an exception.</span><span class="gensmall"></span></div>    
</div>
</div>

    </body>
</html>
